package com.netease.nim.uikit.wzteng.database.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.netease.nim.uikit.wzteng.database.model.LocationSrc;

import com.netease.nim.uikit.wzteng.database.greendao.LocationSrcDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig locationSrcDaoConfig;

    private final LocationSrcDao locationSrcDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        locationSrcDaoConfig = daoConfigMap.get(LocationSrcDao.class).clone();
        locationSrcDaoConfig.initIdentityScope(type);

        locationSrcDao = new LocationSrcDao(locationSrcDaoConfig, this);

        registerDao(LocationSrc.class, locationSrcDao);
    }
    
    public void clear() {
        locationSrcDaoConfig.clearIdentityScope();
    }

    public LocationSrcDao getLocationSrcDao() {
        return locationSrcDao;
    }

}
